[package]
name = "mail"
version = "0.1.0"
edition = "2021"

[dependencies]
lettre = { version = "0.11.15", features = ["smtp-transport", "builder"] }
dotenv = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"